In [ ]:
import pandas as pd
from tqdm import tqdm
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import time

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split

from tensorflow.keras import layers, models, optimizers
from tensorflow.keras.utils import to_categorical
from tensorflow.data import AUTOTUNE
from tensorflow.keras import layers
from tensorflow.keras.applications.inception_v3 import InceptionV3, preprocess_input

from scipy.linalg import sqrtm

import cv2

import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
!unzip "/content/drive/MyDrive/processed (1).zip" -d "/content/processed"

Streaming output truncated to the last 5000 lines.
  inflating: /content/processed/processed/train/outside/PsgRFdk2wpeFuJH1HYKc1g.jpg
  inflating: /content/processed/processed/train/outside/psGrujpCo-p5QzRxyfG6CQ.jpg
  inflating: /content/processed/processed/train/outside/PSHhyEsMT-Vo311oL-8THg.jpg
  inflating: /content/processed/processed/train/outside/Psimct8s4tW4Np6BrY2NAw.jpg
  inflating: /content/processed/processed/train/outside/psIN8b-Rzc-FtpZBczKw_g.jpg
  inflating: /content/processed/processed/train/outside/pSJaakAwxa0UmiVg8hgL_w.jpg
  inflating: /content/processed/processed/train/outside/PSjFgnX0IVdGWMUStpUOBg.jpg
  inflating: /content/processed/processed/train/outside/PsltY9VGKHOpnFjMqAopsw.jpg
  inflating: /content/processed/processed/train/outside/PSmU_iV5giP-Cb4BnfhqTw.jpg
  inflating: /content/processed/processed/train/outside/PSNKmotofM0Uygdtc-xTDg.jpg
  inflating: /content/processed/processed/train/outside/PsnqhaNqpomBi9ElUQU2HQ.jpg
  inflating: /content/processed/processed/train/outside/psPnWdGvGshqkMa3X6qRSg.jpg
  inflating: /content/processed/processed/train/outside/PsQm2lKb1LAQIQc7MydB_g.jpg
  inflating: /content/processed/processed/train/outside/pStsR16PC-5MCEjKPY8Hfw.jpg
  inflating: /content/processed/processed/train/outside/psZvBUo-6i5oCvFiD2xkkQ.jpg
  inflating: /content/processed/processed/train/outside/pT-4oQ3TFUwJA0dbWoKx6Q.jpg
  inflating: /content/processed/processed/train/outside/PT-ui-WMl1ina50IQQjwXg.jpg
  inflating: /content/processed/processed/train/outside/PT04wY-cPxlPPsY8tuuTRA.jpg
  inflating: /content/processed/processed/train/outside/Pt0fw99p6fRFzSbCZw8Mtw.jpg
  inflating: /content/processed/processed/train/outside/pT6aYKvN4YMQ4qBYbvg3NA.jpg
  inflating: /content/processed/processed/train/outside/ptaKiUZQeHrC1JDZgsLg1A.jpg
  inflating: /content/processed/processed/train/outside/pTCh8BaWiwevsvJhR_P_NA.jpg
  inflating: /content/processed/processed/train/outside/Ptge2pOdJB06t8qHKkSZxg.jpg
  inflating: /content/processed/processed/train/outside/pth84C214a3NE0fvnMOB7g.jpg
  inflating: /content/processed/processed/train/outside/PtHcRIlM45ApZoKnX9Eelw.jpg
  inflating: /content/processed/processed/train/outside/PtHqGiwlCzipUyZLJwhyPQ.jpg
  inflating: /content/processed/processed/train/outside/PTnvZTLwhZ3wYEYIgaTyFA.jpg
  inflating: /content/processed/processed/train/outside/ptOQRu_z_PpS5EsVV8wfqw.jpg
  inflating: /content/processed/processed/train/outside/PtQOqGjMnMOhrJ4iX-n_Zw.jpg
  inflating: /content/processed/processed/train/outside/pTvqAZM0sCkDvQkppqfddQ.jpg
  inflating: /content/processed/processed/train/outside/PTVXoVLD98wmy96l3V8MoQ.jpg
  inflating: /content/processed/processed/train/outside/ptwq0-za73jn73FQzNx57g.jpg
  inflating: /content/processed/processed/train/outside/PT_TwqDBLvXYk7Om-TggRA.jpg
  inflating: /content/processed/processed/train/outside/pu4LCGga1mc9eCEHN3CqQA.jpg
  inflating: /content/processed/processed/train/outside/Pu6Os2dkjKLU5rGDl3emyw.jpg
  inflating: /content/processed/processed/train/outside/pu7XBx9KAURnG0POviaykA.jpg
  inflating: /content/processed/processed/train/outside/PUDpInHxidCyuI002Ik6WQ.jpg
  inflating: /content/processed/processed/train/outside/pUe0fOEviICkEAAY-SZElg.jpg
  inflating: /content/processed/processed/train/outside/pUiQxO-dD-2iFXh1swuTHg.jpg
  inflating: /content/processed/processed/train/outside/PUj1HyEwclHWQbp_C_DVHg.jpg
  inflating: /content/processed/processed/train/outside/PuLzHpP12x8LEPw1LyHj0Q.jpg
  inflating: /content/processed/processed/train/outside/PUSURz7LA5nXDU1Hj-hI4A.jpg
  inflating: /content/processed/processed/train/outside/puts06oOriL7XApbpdGMmg.jpg
  inflating: /content/processed/processed/train/outside/PuYk0JpxHQafZMvVQBFYhg.jpg
  inflating: /content/processed/processed/train/outside/PUZjUnhIPuovTx_iWjrOtA.jpg
  inflating: /content/processed/processed/train/outside/PV4X8q_iyotHOQjDNP7zuw.jpg
  inflating: /content/processed/processed/train/outside/pv97TChBJbVx8_3MsV5D-A.jpg
  inflating: /content/processed/processed/train/outside/PVbCHwFbW035b9PDsWdVaQ.jpg
  inflating: /content/processed/processed/train/outside/pvD2bzasMX1okHJlmGd66A.jpg
  inflating: /content/processed/processed/train/outside/pveTmkxCuFcKy_lbXZrViQ.jpg
  inflating: /content/processed/processed/train/outside/PvGRhou2f4Bj4rozhwvDng.jpg
  inflating: /content/processed/processed/train/outside/PvhIqG6W7thuKcd6lLdr9g.jpg
  inflating: /content/processed/processed/train/outside/PVK8NmHF8ygabGbzY2u63A.jpg
  inflating: /content/processed/processed/train/outside/pVLqfWEOVcPcBBSeQsKreg.jpg
  inflating: /content/processed/processed/train/outside/pVqU8TmX85Rb4-c0rsT2Ag.jpg
  inflating: /content/processed/processed/train/outside/pvrjWhk6nYrfbcDI_mqtrg.jpg
  inflating: /content/processed/processed/train/outside/PVtJxoOJJJBxSDAuYo0tkw.jpg
  inflating: /content/processed/processed/train/outside/pVT_oYAZ1gFNSz1S3VyDqA.jpg
  inflating: /content/processed/processed/train/outside/pVvmtwIqK5cmVvvXGCSlKQ.jpg
  inflating: /content/processed/processed/train/outside/pvwxT7NICCEouCSal2aMJg.jpg
  inflating: /content/processed/processed/train/outside/PvyPsVOGNhT8_U1P6xakGA.jpg
  inflating: /content/processed/processed/train/outside/pw050dcjGIdsQ83N8sxE9w.jpg
  inflating: /content/processed/processed/train/outside/pw8aPEFDu-5dUCFHjqRNgg.jpg
  inflating: /content/processed/processed/train/outside/pwFodSGYUPa55stnE_DEkg.jpg
  inflating: /content/processed/processed/train/outside/pWGuQiNWmGYrWDrd7goOQg.jpg
  inflating: /content/processed/processed/train/outside/pwhefTSxPlG1pWBqf33TDQ.jpg
  inflating: /content/processed/processed/train/outside/pwjMm8k4qqwMm0iERy08WA.jpg
  inflating: /content/processed/processed/train/outside/PwJRrbDLmLweuPG3w8DHtA.jpg
  inflating: /content/processed/processed/train/outside/PwP0lmLDWm8-ejmZhcsVpw.jpg
  inflating: /content/processed/processed/train/outside/PWsUM1TMZzM7OI0sOork_Q.jpg
  inflating: /content/processed/processed/train/outside/pWvCEGWvip9mH1pWxSWCAw.jpg
  inflating: /content/processed/processed/train/outside/PWxvyt70MRaM_lXOxq8Lzg.jpg
  inflating: /content/processed/processed/train/outside/pWyo_iuj3EnAzjYKgJ28OA.jpg
  inflating: /content/processed/processed/train/outside/pwZaovBQ_ku6tZlvrwbOXQ.jpg
  inflating: /content/processed/processed/train/outside/pw_XQKAsQvteiQ_cA-Si2g.jpg
  inflating: /content/processed/processed/train/outside/px0niQJoJPG54d8BDm3neQ.jpg
  inflating: /content/processed/processed/train/outside/px0zF8F9uwAVNIjql6xvIg.jpg
  inflating: /content/processed/processed/train/outside/px1iaAq27c-FOSIQ8mjOuA.jpg
  inflating: /content/processed/processed/train/outside/px5js5NcMaDLmyxgvSR8Pg.jpg
  inflating: /content/processed/processed/train/outside/pX9-dMeMQJPlTT6TCLtNbA.jpg
  inflating: /content/processed/processed/train/outside/PXBAsfKDdpHevIbbcfMyJg.jpg
  inflating: /content/processed/processed/train/outside/Pxd5ABQSD1ST1kEl16ICPA.jpg
  inflating: /content/processed/processed/train/outside/PXDlj9TeJNYGWgCDx1AoXA.jpg
  inflating: /content/processed/processed/train/outside/pXE4FYwW5tpI0dHCUUV5-w.jpg
  inflating: /content/processed/processed/train/outside/PXeXI9qjWqL_KKALkV9lXg.jpg
  inflating: /content/processed/processed/train/outside/pxi8cAZnUQ_4AHkr923-2w.jpg
  inflating: /content/processed/processed/train/outside/pxjOUL7iLa5cwLhekHs9HA.jpg
  inflating: /content/processed/processed/train/outside/PXUXrTRYSLXeIxXC3-2kQw.jpg
  inflating: /content/processed/processed/train/outside/PYHduVM8V6W1hGjdOp--LA.jpg
  inflating: /content/processed/processed/train/outside/pyk9pPrmW1w83__M1zl57A.jpg
  inflating: /content/processed/processed/train/outside/PYqfhYvNR40kNAExeeFnVw.jpg
  inflating: /content/processed/processed/train/outside/PyRe5MzqeF9fs5PyphOzPg.jpg
  inflating: /content/processed/processed/train/outside/pytA_fGKJCHzfuNEPkeMbA.jpg
  inflating: /content/processed/processed/train/outside/PyvNGtPgV94rKdAqIxUN6A.jpg
  inflating: /content/processed/processed/train/outside/pyW4a00UXmZn47VP2Mul1A.jpg
  inflating: /content/processed/processed/train/outside/pYWDHTLkH-3bJIwEXcO6hA.jpg
  inflating: /content/processed/processed/train/outside/PyxSxoPH2MCSfF6iIawm7g.jpg
  inflating: /content/processed/processed/train/outside/pyZD1TpaN6aDc3EmtJaS3Q.jpg
  inflating: /content/processed/processed/train/outside/PYZoDaxBAm_FnWUlJO94WA.jpg
  inflating: /content/processed/processed/train/outside/pyzv5A5RBnzMQutk6lS8mA.jpg
  inflating: /content/processed/processed/train/outside/py_6lE5jYd3j6RJ5e9MoGg.jpg
  inflating: /content/processed/processed/train/outside/pz4F9lpWouevjsStLjhcrA.jpg
  inflating: /content/processed/processed/train/outside/pz9a4H0dkpLcaomyiWT-RQ.jpg
  inflating: /content/processed/processed/train/outside/pZCmaRj1-kMyjwPS6Qwfhw.jpg
  inflating: /content/processed/processed/train/outside/PzEbR0bmwh6-VBeqGaIfvA.jpg
  inflating: /content/processed/processed/train/outside/pZeCK90L7UovOUpAd8VU7g.jpg
  inflating: /content/processed/processed/train/outside/PzE_-3K1c6Hu0b-oGFbJ-A.jpg
  inflating: /content/processed/processed/train/outside/PzNNKjrzYF-4ho--AA1WQg.jpg
  inflating: /content/processed/processed/train/outside/pZQEyQXDflRPI4trHHAfiw.jpg
  inflating: /content/processed/processed/train/outside/pzQYFt21fdkmTkmT_9hWTA.jpg
  inflating: /content/processed/processed/train/outside/PzrkJF5AZM9rT4DP0CHFog.jpg
  inflating: /content/processed/processed/train/outside/PZRtsBZyY04hEV_0Cbg60Q.jpg
  inflating: /content/processed/processed/train/outside/PzxnrY2kTvQLi8wqw2U4wQ.jpg
  inflating: /content/processed/processed/train/outside/pzY4Os5jOXVjx1MbgLzhPw.jpg
  inflating: /content/processed/processed/train/outside/pZy4xlRscd6yntN44T9wkQ.jpg
  inflating: /content/processed/processed/train/outside/PZYZBWmbWxbenBSGUvpO9A.jpg
  inflating: /content/processed/processed/train/outside/pzzRjXYAu9b-616jDGz7rw.jpg
  inflating: /content/processed/processed/train/outside/P_IKF9Jvq2onF8lHqBjvPA.jpg
  inflating: /content/processed/processed/train/outside/P_l6rGS_cPSCTZeM4IemDA.jpg
  inflating: /content/processed/processed/train/outside/P_ljAqNpOD5TkMsc6s4ebQ.jpg
  inflating: /content/processed/processed/train/outside/p_lKdaqlmzCSwPWImE4nmg.jpg
  inflating: /content/processed/processed/train/outside/p_lzs4uu0udaNeiLNXTm7w.jpg
  inflating: /content/processed/processed/train/outside/P_NRBiB5QDrA6KsnG9yWrQ.jpg
  inflating: /content/processed/processed/train/outside/p_t7zsZR-FBeac05Lcom-g.jpg
  inflating: /content/processed/processed/train/outside/P_vzS1jY3otAqNzFOQNADg.jpg
  inflating: /content/processed/processed/train/outside/p_wLmwMRfw0UX7oz4ChuUQ.jpg
  inflating: /content/processed/processed/train/outside/p_xC8NB0hTjcJz7s4BXKcQ.jpg
  inflating: /content/processed/processed/train/outside/Q-aYOu8yk9rNeQ9SlmaZww.jpg
  inflating: /content/processed/processed/train/outside/Q-d0H29m_SYOmhYvERM-hQ.jpg
  inflating: /content/processed/processed/train/outside/q-E54Y6jRFjFHHtO8uR31g.jpg
  inflating: /content/processed/processed/train/outside/Q-GiO19OBwXLA6P4dt-xQg.jpg
  inflating: /content/processed/processed/train/outside/Q-JujrlH-trWG3EbGnPNKA.jpg
  inflating: /content/processed/processed/train/outside/q-JWlyGR2fUSb_0xbgIt-Q.jpg
  inflating: /content/processed/processed/train/outside/Q-NiFxWJKKaGkvo8uveiAw.jpg
  inflating: /content/processed/processed/train/outside/Q-obQjIWZ_aPLmlsAu8wIg.jpg
  inflating: /content/processed/processed/train/outside/Q-ztDD5DgHxGOg74WXNx5g.jpg
  inflating: /content/processed/processed/train/outside/Q03uXbe3rIUq6H-2_uguHg.jpg
  inflating: /content/processed/processed/train/outside/q0U9GJdiyJav7i0xbxDKWw.jpg
  inflating: /content/processed/processed/train/outside/q0VgE5BloreWrThMfutL7g.jpg
  inflating: /content/processed/processed/train/outside/Q0zDftyNJNCALw3dxEfYcQ.jpg
  inflating: /content/processed/processed/train/outside/q14YcDbjtl_VcZWEgRB06w.jpg
  inflating: /content/processed/processed/train/outside/Q1cWJ-yj6GSk7dKgFJfynw.jpg
  inflating: /content/processed/processed/train/outside/Q1eGcJgIIl4txx5fsyBtaQ.jpg
  inflating: /content/processed/processed/train/outside/Q1LmtUuMZJSdHgaaJKPUpQ.jpg
  inflating: /content/processed/processed/train/outside/Q1MbyR8OSvALFmj7BV-aYw.jpg
  inflating: /content/processed/processed/train/outside/q1XWd1PgQU4squz79g51yw.jpg
  inflating: /content/processed/processed/train/outside/Q1YLKyx4Q1u4SdBNBm0hUg.jpg
  inflating: /content/processed/processed/train/outside/q2C0575r6RI7ZpCk4yopcw.jpg
  inflating: /content/processed/processed/train/outside/q2DkEa0RGJhXU9ebQ1BRIg.jpg
  inflating: /content/processed/processed/train/outside/q2JN6obdgMFnhYY5tzmyIA.jpg
  inflating: /content/processed/processed/train/outside/q2r7cWlMumwduOCr7sfiCQ.jpg
  inflating: /content/processed/processed/train/outside/q2s0c_1QqY7yTSK92ttHhw.jpg
  inflating: /content/processed/processed/train/outside/Q2v035mvlGRUusp_DVLiNg.jpg
  inflating: /content/processed/processed/train/outside/q2Ws_ZeOxLPuPYgXjAn_VQ.jpg
  inflating: /content/processed/processed/train/outside/q33KYtfUIKuzXeBb02GaDQ.jpg
  inflating: /content/processed/processed/train/outside/Q354iBRyCBw4YNOAbI4g1g.jpg
  inflating: /content/processed/processed/train/outside/q35Na-5xKeQh5M_J8NdBDw.jpg
  inflating: /content/processed/processed/train/outside/q35vK3Iup0JdiLWhARhvDg.jpg
  inflating: /content/processed/processed/train/outside/Q39ZTfUpNMF5Mv7uaEKWpg.jpg
  inflating: /content/processed/processed/train/outside/q3alv_QINiSA4fCnbb-uKQ.jpg
  inflating: /content/processed/processed/train/outside/Q3B_iYKciiHCdZIUVvdMlA.jpg
  inflating: /content/processed/processed/train/outside/Q3d610-3DY43KZKSkJTAJg.jpg
  inflating: /content/processed/processed/train/outside/Q3JKiHfMJ2gvHuMkHIytQg.jpg
  inflating: /content/processed/processed/train/outside/Q3lKwTc3U9hndZn-hV9aYQ.jpg
  inflating: /content/processed/processed/train/outside/Q3lVNts135U6KvjAx1GwNw.jpg
  inflating: /content/processed/processed/train/outside/Q3RFIBVRmAElWv4FjT942w.jpg
  inflating: /content/processed/processed/train/outside/Q3RpX2k1U-pLvJEGFmW22w.jpg
  inflating: /content/processed/processed/train/outside/q3x-mB4vUZ2jwZlYzVJJww.jpg
  inflating: /content/processed/processed/train/outside/Q40b-uiQf47RTyb2YqGQRQ.jpg
  inflating: /content/processed/processed/train/outside/q46cdgWmlccb9SKzvqpWHQ.jpg
  inflating: /content/processed/processed/train/outside/q4fXuabfAJCFD1me9jamqg.jpg
  inflating: /content/processed/processed/train/outside/Q4in-tbpybvFi7bkWfG4cA.jpg
  inflating: /content/processed/processed/train/outside/q4L020Tl83dlWDeK73YIBA.jpg
  inflating: /content/processed/processed/train/outside/Q4O03ANjA_oMhf0UxX60Cw.jpg
  inflating: /content/processed/processed/train/outside/q4ZjXgwTqc5cULek9e3CzA.jpg
  inflating: /content/processed/processed/train/outside/Q4ZOBmsQt6zb2BuESomGQA.jpg
  inflating: /content/processed/processed/train/outside/Q5-8ChfNDutHugMzrxu6tQ.jpg
  inflating: /content/processed/processed/train/outside/q5-ADr4dJU3BFmngFfdcdw.jpg
  inflating: /content/processed/processed/train/outside/q5CFwXhuh75y8FeCgVdcXw.jpg
  inflating: /content/processed/processed/train/outside/q5IDz0Mcx67Aa8SD_zJdDQ.jpg
  inflating: /content/processed/processed/train/outside/q5MROebT_UyP9_DC67yBtg.jpg
  inflating: /content/processed/processed/train/outside/Q5qD9Cic2gPbhKlsIYnQrQ.jpg
  inflating: /content/processed/processed/train/outside/q5vSSZ2IUtm1NzHIBcdQjw.jpg
  inflating: /content/processed/processed/train/outside/q5VyOVnRAPy_wZ5eZwae-w.jpg
  inflating: /content/processed/processed/train/outside/q5XFOZLb9KxY1kSmKwaDTA.jpg
  inflating: /content/processed/processed/train/outside/q65s4Y8rqkQeV9YZ_-SyJw.jpg
  inflating: /content/processed/processed/train/outside/Q69qxjZzpSan41wKOXFdsQ.jpg
  inflating: /content/processed/processed/train/outside/Q6AXm9d-yppkcxK2s12XeQ.jpg
  inflating: /content/processed/processed/train/outside/q6joR1h95bpl1YgOc51GVQ.jpg
  inflating: /content/processed/processed/train/outside/q6nkhjwWTEDqTcRNtv_F6Q.jpg
  inflating: /content/processed/processed/train/outside/Q6r2WrBmyEqeGt2uqoPaqA.jpg
  inflating: /content/processed/processed/train/outside/Q6tEDEcyyHT7aCissUhHZw.jpg
  inflating: /content/processed/processed/train/outside/Q6tg7bI7m_LKewJxg1a7rA.jpg
  inflating: /content/processed/processed/train/outside/Q7eE-HkDiEwz1UsWovYFqg.jpg
  inflating: /content/processed/processed/train/outside/Q7OCoGM--2hCMotQ7n_JJQ.jpg
  inflating: /content/processed/processed/train/outside/Q7pwB88bQG0Z_ZKXOQuY2g.jpg
  inflating: /content/processed/processed/train/outside/Q7vFhS-hdgDA6PQTm9w3DQ.jpg
  inflating: /content/processed/processed/train/outside/Q7X5_6ldCRtPHMJwC3gJCg.jpg
  inflating: /content/processed/processed/train/outside/q7_j34NmyVNRBMY1xRjz_g.jpg
  inflating: /content/processed/processed/train/outside/Q8335eogY-pq9RFW5sDWgA.jpg
  inflating: /content/processed/processed/train/outside/q84xyY-Yn0NsHJbteoSb_Q.jpg
  inflating: /content/processed/processed/train/outside/Q8CPN9TQej7jnzPJZqx3Vg.jpg
  inflating: /content/processed/processed/train/outside/Q8DY-JiixxzkbSNtwJGgtw.jpg
  inflating: /content/processed/processed/train/outside/q8EOrpbG5zwS6BNBreHI5g.jpg
  inflating: /content/processed/processed/train/outside/Q8KIyCjm_UMhT1yTO1LlGw.jpg
  inflating: /content/processed/processed/train/outside/Q8Tal5Pw73svzY9HiorhCA.jpg
  inflating: /content/processed/processed/train/outside/q8TtUbG67fBI6fy5AHnuaQ.jpg
  inflating: /content/processed/processed/train/outside/Q8zptKihXaDzay_dhYZtyw.jpg
  inflating: /content/processed/processed/train/outside/q9aZbsUYLI3w28LYucF0Yg.jpg
  inflating: /content/processed/processed/train/outside/q9bKqREpbJiu0H6ctytjKA.jpg
  inflating: /content/processed/processed/train/outside/q9dMkpRyubixfqUVDVfbvw.jpg
  inflating: /content/processed/processed/train/outside/q9lM4BgA4H_RSax68QjQZA.jpg
  inflating: /content/processed/processed/train/outside/Q9Q-tg_nzX6q9Yu5RMCsow.jpg
  inflating: /content/processed/processed/train/outside/Q9qjPrrTufHFoJ7bSEu-FA.jpg
  inflating: /content/processed/processed/train/outside/q9SN5XbDs07lmLO6dUKiJA.jpg
  inflating: /content/processed/processed/train/outside/QA-IJdIdmPlFAlUex_96PQ.jpg
  inflating: /content/processed/processed/train/outside/qa0JtR5uVYv92EmQW9uTGQ.jpg
  inflating: /content/processed/processed/train/outside/qA0rObNNp8kdplLXO6-ZlA.jpg
  inflating: /content/processed/processed/train/outside/QA7HYnNf7Uz9vjlV6vh5TQ.jpg
  inflating: /content/processed/processed/train/outside/qa99ZNfD33RjC4CYlsMqHA.jpg
  inflating: /content/processed/processed/train/outside/QafNuNy88rFt0HwcsB0Hhw.jpg
  inflating: /content/processed/processed/train/outside/QAiSA-ceDSThCTKTgMaCww.jpg
  inflating: /content/processed/processed/train/outside/qAj5rM0TV-8C5dUj4qvQjA.jpg
  inflating: /content/processed/processed/train/outside/QAjogpk7FEL4-uqk5u6h7g.jpg
  inflating: /content/processed/processed/train/outside/QajUQr9zXjxlefQJz47NpA.jpg
  inflating: /content/processed/processed/train/outside/qAoAh1Y1KlKP5kEoSm1mvw.jpg
  inflating: /content/processed/processed/train/outside/QaOz0ZoOnj8IC-v3FYZwQA.jpg
  inflating: /content/processed/processed/train/outside/Qap1n5_jiXweh8VpgJftww.jpg
  inflating: /content/processed/processed/train/outside/QaysW7lx3PpfwuoXuYH-vg.jpg
  inflating: /content/processed/processed/train/outside/qB-VHM0IIM8ItRu-oBEhmw.jpg
  inflating: /content/processed/processed/train/outside/Qb7cUIRJplpUxbVpvWV08A.jpg
  inflating: /content/processed/processed/train/outside/QbA6qfVamd-NtWCjggnoNw.jpg
  inflating: /content/processed/processed/train/outside/QBAGfn_sQZvwXWszYAi05A.jpg
  inflating: /content/processed/processed/train/outside/QBAk6C_iLCVZZEg59B7-CA.jpg
  inflating: /content/processed/processed/train/outside/QBcG9pdViCZk9qwwOYI84Q.jpg
  inflating: /content/processed/processed/train/outside/QbfdgPBsiF4IpWqM-7SVWQ.jpg
  inflating: /content/processed/processed/train/outside/QBfi8u2yKwLrn_ibQUrrRA.jpg
  inflating: /content/processed/processed/train/outside/qbHHM7JR38trTzfEEvkgMw.jpg
  inflating: /content/processed/processed/train/outside/QBJ0FUYsbMt4aWkKubV92A.jpg
  inflating: /content/processed/processed/train/outside/qbkLUBzCQcPhbOSDlZOlDQ.jpg

In [8]:
import pandas as pd

# Load the preprocessed training metadata
df_train = pd.read_csv('/content/processed/processed/train_meta.csv')

# Preview the first few rows
df_train.head()

,photo_id,business_id,caption,label,image_path
0,_5AXzUhxvmNU0HVS2ECGLg,U_Sw9VC6mCyTbUo2mejS0A,Peppermint cream tea with fruit purée and boba,drink,photos\_5AXzUhxvmNU0HVS2ECGLg.jpg
1,NzBxTwQVB8HTWgM5gyv4wQ,KqF1W-GxTAnOZtcMNS5Wiw,NaN,inside,photos\NzBxTwQVB8HTWgM5gyv4wQ.jpg
2,wk77TsuJbAHCCdPnfWWdRA,RQAF6a0akMiot5lZZnMNNw,NaN,outside,photos\wk77TsuJbAHCCdPnfWWdRA.jpg
3,NpvUCC2ezjtG5yAdccNmjQ,I8lz3u94Y-dWft5fVN3IIA,Beer Flight & Flatbread,food,photos\NpvUCC2ezjtG5yAdccNmjQ.jpg
4,IPCFHtfmWnvB0GQIrvqM-Q,HdTGEuChp8bqRMUjnkqgFA,"Reused paper menus...dried sauce by ""paneer""",menu,photos\IPCFHtfmWnvB0GQIrvqM-Q.jpg

In [10]:
df_train = pd.read_csv('/content/processed/processed/train_meta.csv')  # or correct file name
df_train.head()

,photo_id,business_id,caption,label,image_path
0,_5AXzUhxvmNU0HVS2ECGLg,U_Sw9VC6mCyTbUo2mejS0A,Peppermint cream tea with fruit purée and boba,drink,photos\_5AXzUhxvmNU0HVS2ECGLg.jpg
1,NzBxTwQVB8HTWgM5gyv4wQ,KqF1W-GxTAnOZtcMNS5Wiw,NaN,inside,photos\NzBxTwQVB8HTWgM5gyv4wQ.jpg
2,wk77TsuJbAHCCdPnfWWdRA,RQAF6a0akMiot5lZZnMNNw,NaN,outside,photos\wk77TsuJbAHCCdPnfWWdRA.jpg
3,NpvUCC2ezjtG5yAdccNmjQ,I8lz3u94Y-dWft5fVN3IIA,Beer Flight & Flatbread,food,photos\NpvUCC2ezjtG5yAdccNmjQ.jpg
4,IPCFHtfmWnvB0GQIrvqM-Q,HdTGEuChp8bqRMUjnkqgFA,"Reused paper menus...dried sauce by ""paneer""",menu,photos\IPCFHtfmWnvB0GQIrvqM-Q.jpg

In [11]:
# Load the training metadata
df_train=pd.read_csv('/content/processed/processed/train_meta.csv')

In [12]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160080 entries, 0 to 160079
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   photo_id     160080 non-null  object
 1   business_id  160080 non-null  object
 2   caption      77525 non-null   object
 3   label        160080 non-null  object
 4   image_path   160080 non-null  object
dtypes: object(5)
memory usage: 6.1+ MB

In [14]:
# Load the training metadata
df_test=pd.read_csv('/content/processed/processed/train_meta.csv')

In [15]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160080 entries, 0 to 160079
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   photo_id     160080 non-null  object
 1   business_id  160080 non-null  object
 2   caption      77525 non-null   object
 3   label        160080 non-null  object
 4   image_path   160080 non-null  object
dtypes: object(5)
memory usage: 6.1+ MB

In [16]:
df_train.head(5)

,photo_id,business_id,caption,label,image_path
0,_5AXzUhxvmNU0HVS2ECGLg,U_Sw9VC6mCyTbUo2mejS0A,Peppermint cream tea with fruit purée and boba,drink,photos\_5AXzUhxvmNU0HVS2ECGLg.jpg
1,NzBxTwQVB8HTWgM5gyv4wQ,KqF1W-GxTAnOZtcMNS5Wiw,NaN,inside,photos\NzBxTwQVB8HTWgM5gyv4wQ.jpg
2,wk77TsuJbAHCCdPnfWWdRA,RQAF6a0akMiot5lZZnMNNw,NaN,outside,photos\wk77TsuJbAHCCdPnfWWdRA.jpg
3,NpvUCC2ezjtG5yAdccNmjQ,I8lz3u94Y-dWft5fVN3IIA,Beer Flight & Flatbread,food,photos\NpvUCC2ezjtG5yAdccNmjQ.jpg
4,IPCFHtfmWnvB0GQIrvqM-Q,HdTGEuChp8bqRMUjnkqgFA,"Reused paper menus...dried sauce by ""paneer""",menu,photos\IPCFHtfmWnvB0GQIrvqM-Q.jpg

In [17]:
df_test.head(5)

,photo_id,business_id,caption,label,image_path
0,_5AXzUhxvmNU0HVS2ECGLg,U_Sw9VC6mCyTbUo2mejS0A,Peppermint cream tea with fruit purée and boba,drink,photos\_5AXzUhxvmNU0HVS2ECGLg.jpg
1,NzBxTwQVB8HTWgM5gyv4wQ,KqF1W-GxTAnOZtcMNS5Wiw,NaN,inside,photos\NzBxTwQVB8HTWgM5gyv4wQ.jpg
2,wk77TsuJbAHCCdPnfWWdRA,RQAF6a0akMiot5lZZnMNNw,NaN,outside,photos\wk77TsuJbAHCCdPnfWWdRA.jpg
3,NpvUCC2ezjtG5yAdccNmjQ,I8lz3u94Y-dWft5fVN3IIA,Beer Flight & Flatbread,food,photos\NpvUCC2ezjtG5yAdccNmjQ.jpg
4,IPCFHtfmWnvB0GQIrvqM-Q,HdTGEuChp8bqRMUjnkqgFA,"Reused paper menus...dried sauce by ""paneer""",menu,photos\IPCFHtfmWnvB0GQIrvqM-Q.jpg

In [18]:
# === Paths (change as needed) ===
base_dir = "PHOTOSFILES/processed"
train_dir = os.path.join(base_dir, "train")
test_dir = os.path.join(base_dir, "test")
train_meta_path = os.path.join("train_meta.csv")
test_meta_path = os.path.join("test_meta.csv")

In [19]:
import os
import pandas as pd
# === Function to count images ===
def count_images_in_folder(folder_path, image_exts={'.jpg', '.jpeg', '.png', '.bmp', '.gif'}):
    return sum(
        1 for root, _, files in os.walk(folder_path)
        for file in files if os.path.splitext(file)[1].lower() in image_exts
    )
# === Count images ===
num_train_images = count_images_in_folder(train_dir)
num_test_images = count_images_in_folder(test_dir)

In [20]:
# === Print Summary ===
print(f" Train images found: {num_train_images}")
print(f" Test images found: {num_test_images}")

 Train images found: 0
 Test images found: 0

In [21]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

In [22]:
import os
import numpy as np
import pandas as pd
from PIL import Image
import tensorflow as tf
from tensorflow.keras import layers

# Set constants
IMG_SIZE = 64  # Resize images to 64x64 for efficiency
NOISE_DIM = 100
BATCH_SIZE = 64
EPOCHS = 50
NUM_CLASSES = 4  # Assuming labels: food, drink, inside, outside

In [23]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

In [24]:
 #Combine label columns
# Initialize label encoder
label_encoder = LabelEncoder()
all_labels = pd.concat([df_train['label'], df_test['label']], ignore_index=True)

In [25]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Fit on combined labels to cover all possible classes
label_encoder.fit(pd.concat([df_train['label'], df_test['label']]))

# Now you can safely transform
df_train['label_encoded'] = label_encoder.transform(df_train['label'])
df_test['label_encoded'] = label_encoder.transform(df_test['label'])

In [26]:
def load_images_and_labels(df, image_dir, label_encoder, img_size=(64, 64)):
    images, labels = [], []

    for _, row in tqdm(df.iterrows(), total=len(df), desc="📦 Loading images"):
        label = row['label']
        photo_id = row['photo_id']
        img_path = os.path.join(image_dir, label, photo_id + '.jpg')

        if os.path.exists(img_path):
            try:
                img = Image.open(img_path).convert('RGB').resize(img_size)
                img = np.array(img) / 255.0
                images.append(img)
                labels.append(label_encoder.transform([label])[0])
            except:
                continue

    images = np.array(images)
    labels = to_categorical(labels, num_classes=len(label_encoder.classes_))
    return images, labels

In [27]:
from tensorflow.keras.utils import to_categorical
from PIL import Image
import numpy as np
from tqdm import tqdm

def load_images_and_labels(df, image_dir, label_encoder, img_size=(64, 64), limit=10000):
    images, labels = [], []
    count = 0

    for _, row in tqdm(df.iterrows(), total=len(df), desc="📦 Loading images"):
        if count >= limit:
            break

        label = row['label']
        photo_id = row['photo_id']
        img_path = os.path.join(image_dir, label, photo_id + '.jpg')

        if os.path.exists(img_path):
            try:
                img = Image.open(img_path).convert('RGB').resize(img_size)
                img = np.array(img) / 255.0
                images.append(img)
                labels.append(label_encoder.transform([label])[0])
                count += 1
            except:
                continue

    images = np.array(images, dtype=np.float32)
    labels = to_categorical(labels, num_classes=len(label_encoder.classes_))
    return images, labels

In [28]:
 #One-hot encode
from tensorflow.keras.utils import to_categorical

y_train = to_categorical(df_train['label_encoded'], num_classes=len(label_encoder.classes_))
y_test = to_categorical(df_test['label_encoded'], num_classes=len(label_encoder.classes_))

In [29]:
X_train, y_train = load_images_and_labels(df_train, train_dir, label_encoder, limit=10000)
X_test, y_test = load_images_and_labels(df_test, test_dir, label_encoder, limit=10000)

print("Final Train shape:", X_train.shape, y_train.shape)
print(" Final Test shape:", X_test.shape, y_test.shape)

📦 Loading images: 100%|██████████| 160080/160080 [00:15<00:00, 10270.29it/s]
📦 Loading images: 100%|██████████| 160080/160080 [00:12<00:00, 13240.05it/s]

Final Train shape: (0,) (0, 5)
 Final Test shape: (0,) (0, 5)

In [30]:
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np

# Constants
IMG_SIZE = 64
NOISE_DIM = 100
BATCH_SIZE = 64
EPOCHS = 50
NUM_CLASSES = y_train.shape[1]  # From one-hot shape

Generate Model

In [31]:
def build_generator():
    noise_input = layers.Input(shape=(NOISE_DIM,))
    label_input = layers.Input(shape=(NUM_CLASSES,))

    x = layers.Concatenate()([noise_input, label_input])
    x = layers.Dense(8*8*256, use_bias=False)(x)
    x = layers.BatchNormalization()(x)
    x = layers.LeakyReLU()(x)
    x = layers.Reshape((8, 8, 256))(x)

    x = layers.Conv2DTranspose(128, 5, strides=2, padding='same', use_bias=False)(x)
    x = layers.BatchNormalization()(x)
    x = layers.LeakyReLU()(x)

    x = layers.Conv2DTranspose(64, 5, strides=2, padding='same', use_bias=False)(x)
    x = layers.BatchNormalization()(x)
    x = layers.LeakyReLU()(x)

    output = layers.Conv2DTranspose(3, 5, strides=2, padding='same', activation='tanh')(x)
    return tf.keras.Model([noise_input, label_input], output)

generator = build_generator()

Discriminator Model

In [32]:
def build_discriminator():
    image_input = layers.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
    label_input = layers.Input(shape=(NUM_CLASSES,))

    label_embedding = layers.Dense(IMG_SIZE * IMG_SIZE * 1)(label_input)
    label_embedding = layers.Reshape((IMG_SIZE, IMG_SIZE, 1))(label_embedding)

    x = layers.Concatenate()([image_input, label_embedding])
    x = layers.Conv2D(64, 5, strides=2, padding='same')(x)
    x = layers.LeakyReLU()(x)
    x = layers.Dropout(0.3)(x)

    x = layers.Conv2D(128, 5, strides=2, padding='same')(x)
    x = layers.LeakyReLU()(x)
    x = layers.Dropout(0.3)(x)

    x = layers.Flatten()(x)
    output = layers.Dense(1)(x)
    return tf.keras.Model([image_input, label_input], output)

discriminator = build_discriminator()

In [33]:
generator.save("cgan_generator.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Losses & Optimizers

In [34]:
cross_entropy = tf.keras.losses.BinaryCrossentropy(from_logits=True)

def generator_loss(fake_output):
    return cross_entropy(tf.ones_like(fake_output), fake_output)

def discriminator_loss(real_output, fake_output):
    real_loss = cross_entropy(tf.ones_like(real_output), real_output)
    fake_loss = cross_entropy(tf.zeros_like(fake_output), fake_output)
    return real_loss + fake_loss

gen_optimizer = tf.keras.optimizers.Adam(1e-4)
disc_optimizer = tf.keras.optimizers.Adam(1e-4)

Training Step

In [35]:
@tf.function
def train_step(images, labels):
    noise = tf.random.normal([BATCH_SIZE, NOISE_DIM])

    with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:
        generated_images = generator([noise, labels], training=True)

        real_output = discriminator([images, labels], training=True)
        fake_output = discriminator([generated_images, labels], training=True)

        gen_loss = generator_loss(fake_output)
        disc_loss = discriminator_loss(real_output, fake_output)

    gradients_gen = gen_tape.gradient(gen_loss, generator.trainable_variables)
    gradients_disc = disc_tape.gradient(disc_loss, discriminator.trainable_variables)

    gen_optimizer.apply_gradients(zip(gradients_gen, generator.trainable_variables))
    disc_optimizer.apply_gradients(zip(gradients_disc, discriminator.trainable_variables))

    return gen_loss, disc_loss

 Training Loop

In [36]:
def train_cgan(X_train, y_train, epochs=50, batch_size=64):
    # Ensure only 10,000 max samples used ---
    max_samples = 10000
    X_train = X_train[:10000]
    y_train = y_train[:10000]

    steps_per_epoch = X_train.shape[0] // batch_size

    for epoch in range(epochs):
        print(f"\nEpoch {epoch + 1}/{epochs}")
        for i in range(steps_per_epoch):
            idx = np.random.randint(0, X_train.shape[0], batch_size)
            img_batch = X_train[idx]
            label_batch = y_train[idx]
            g_loss, d_loss = train_step(img_batch, label_batch)
        print(f" Gen Loss: {g_loss:.4f} | Disc Loss: {d_loss:.4f}")

In [37]:
discriminator.save("cgan_discriminator.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [38]:
# Use this if you still have label_encoder loaded from earlier
label_names = list(label_encoder.classes_)  # ['drink', 'food', 'inside', 'outside']
print("Available labels:", label_names)

Available labels: ['drink', 'food', 'inside', 'menu', 'outside']

In [39]:
def generate_synthetic_images(n=100):
    noise = tf.random.normal([n, NOISE_DIM])
    random_labels = tf.random.uniform([n], minval=0, maxval=NUM_CLASSES, dtype=tf.int32)
    onehot_labels = tf.keras.utils.to_categorical(random_labels, NUM_CLASSES)
    fake_images = generator([noise, onehot_labels], training=False)
    return fake_images, onehot_labels

In [40]:
# IS and FID calculation
def calculate_is_fid_optimized(real_images, fake_images):
    # Use InceptionV3 to get 2048-d features
    inception_model = InceptionV3(include_top=False, pooling='avg', input_shape=(299,299,3))

    def preprocess_and_extract(images):
        images_resized = tf.image.resize(images, (299,299))
        images_resized = preprocess_input(images_resized*255)
        features = inception_model.predict(images_resized, verbose=0)
        return features.astype(np.float32)

    # Extract features
    real_features = preprocess_and_extract(real_images)
    fake_features = preprocess_and_extract(fake_images)

    # Compute means and covariances
    mu_real = np.mean(real_features, axis=0)
    mu_fake = np.mean(fake_features, axis=0)
    sigma_real = np.cov(real_features, rowvar=False)
    sigma_fake = np.cov(fake_features, rowvar=False)

    # Compute FID
    diff = mu_real - mu_fake
    cov_sqrt, _ = sqrtm(sigma_real @ sigma_fake, disp=False)
    if np.iscomplexobj(cov_sqrt):
        cov_sqrt = cov_sqrt.real
    fid_score = np.sum(diff**2) + np.trace(sigma_real + sigma_fake - 2*cov_sqrt)

    # Compute dummy IS (or plug your own IS function)
    inception_score = np.random.uniform(1.5, 3.5)

    return inception_score, fid_score

In [41]:
pip install scipy

Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (1.15.3)
Requirement already satisfied: numpy<2.5,>=1.23.5 in /usr/local/lib/python3.11/dist-packages (from scipy) (2.0.2)

Load Pretrained InceptionV3 for Feature Extractio

In [42]:
from tensorflow.keras.applications.inception_v3 import InceptionV3, preprocess_input
from tensorflow.keras.models import Model
import tensorflow as tf
import numpy as np
from scipy.linalg import sqrtm

# Load model and cut off before softmax
base_model = InceptionV3(include_top=True, weights='imagenet')
model = Model(inputs=base_model.input, outputs=base_model.get_layer('avg_pool').output)

Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/inception_v3/inception_v3_weights_tf_dim_ordering_tf_kernels.h5
96112376/96112376 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step

Preprocessing Function

In [43]:
def preprocess_images(images):
    # Resize to 299x299 and scale to [-1, 1]
    images = tf.image.resize(images, [299, 299])
    return preprocess_input(images * 255.0)  # Expect input in [0, 255]

Generate Fake and Real Image Batches

In [44]:
def get_fake_images(generator, n_samples=10000):
    noise = tf.random.normal([n_samples, NOISE_DIM])
    labels = tf.random.uniform([n_samples], minval=0, maxval=NUM_CLASSES, dtype=tf.int32)
    onehot_labels = tf.keras.utils.to_categorical(labels, NUM_CLASSES)
    fake_images = generator([noise, onehot_labels], training=False)
    return (fake_images + 1) / 2.0  # Scale from [-1,1] to [0,1]

def get_real_images(X_real, n_samples=100):
    idx = np.random.choice(len(X_real), size=n_samples, replace=False)
    return X_real[idx]

Compute Inception Score (IS)

In [45]:
def inception_score(images, splits=10):
    images = preprocess_images(images)
    preds = base_model.predict(images)
    scores = []

    split_size = len(images) // splits
    for i in range(splits):
        part = preds[i * split_size : (i + 1) * split_size]
        py = np.mean(part, axis=0)
        kl = part * (np.log(part + 1e-10) - np.log(py + 1e-10))
        scores.append(np.exp(np.mean(np.sum(kl, axis=1))))
    return np.mean(scores), np.std(scores)

Compute Fréchet Inception Distance (FID)

In [46]:
def calculate_fid(real_images, fake_images):
    act1 = model.predict(preprocess_images(real_images))
    act2 = model.predict(preprocess_images(fake_images))

    mu1, sigma1 = act1.mean(axis=0), np.cov(act1, rowvar=False)
    mu2, sigma2 = act2.mean(axis=0), np.cov(act2, rowvar=False)

    ssdiff = np.sum((mu1 - mu2)**2.0)
    covmean = sqrtm(sigma1.dot(sigma2))

    if np.iscomplexobj(covmean):
        covmean = covmean.real

    fid = ssdiff + np.trace(sigma1 + sigma2 - 2.0 * covmean)
    return fid

Evalaution

In [48]:
import os
from tensorflow.keras.preprocessing import image
import numpy as np

# Define the test image path
test_dir = '/content/processed/processed/test/'

def load_images_from_folder(folder_path, img_size=(64, 64), limit=None):
    images = []
    count = 0
    for class_folder in os.listdir(folder_path):
        class_path = os.path.join(folder_path, class_folder)
        if not os.path.isdir(class_path):
            continue
        for img_file in os.listdir(class_path):
            img_path = os.path.join(class_path, img_file)
            try:
                img = image.load_img(img_path, target_size=img_size)
                img_array = image.img_to_array(img)
                images.append(img_array)
                count += 1
                if limit and count >= limit:
                    return np.array(images)
            except:
                continue
    return np.array(images)

# Load real test images (e.g., 1000)
X_test = load_images_from_folder(test_dir, limit=1000) / 255.0
print("Loaded images:", X_test.shape)

Loaded images: (1000, 64, 64, 3)

In [49]:
# Sample 3000 images each
fake_images = get_fake_images(generator, n_samples=1000)
real_images = get_real_images(X_test, n_samples=1000)

# Evaluate
is_mean, is_std = inception_score(fake_images)
fid_score = calculate_fid(real_images, fake_images)

print(f" Inception Score: {is_mean:.4f} ± {is_std:.4f}")
print(f" FID Score: {fid_score:.4f}")

32/32 ━━━━━━━━━━━━━━━━━━━━ 263s 8s/step
32/32 ━━━━━━━━━━━━━━━━━━━━ 258s 8s/step
32/32 ━━━━━━━━━━━━━━━━━━━━ 258s 8s/step
 Inception Score: 1.0125 ± 0.0006
 FID Score: 643.0994

In [50]:
def train_cgan(X_train, y_train, epochs=50, batch_size=64):
    X_train = X_train[:10000]
    y_train = y_train[:10000]
    steps_per_epoch = X_train.shape[0] // batch_size

    for epoch in range(epochs):
        print(f"\n Epoch {epoch + 1}/{epochs}")
        for step in range(steps_per_epoch):
            idx = np.random.randint(0, X_train.shape[0], batch_size)
            x_batch = X_train[idx]
            y_batch = y_train[idx]
            g_loss, d_loss = train_step(x_batch, y_batch)

        print(f"Gen Loss: {g_loss:.4f} | Disc Loss: {d_loss:.4f}")
        display_generated_images_per_label(generator, label_encoder, n_per_label=5)

In [51]:
import itertools

# Define your search grid
param_grid = {
    'learning_rate': [0.0002, 0.0001],
    'batch_size': [32, 64],
    'latent_dim': [100, 128],
    'beta_1': [0.5, 0.6]
}

# Generate all combinations of parameters
param_combinations = list(itertools.product(*param_grid.values()))

In [52]:
import numpy as np
import pandas as pd

tuning_results = []

# Loop through each config
for i, (lr, batch_size, latent_dim, beta1) in enumerate(param_combinations):
    print(f"\n Run {i+1}/{len(param_combinations)}")
    print(f"LR={lr}, Batch={batch_size}, Latent={latent_dim}, Beta1={beta1}")

    # Set global variables
    NOISE_DIM = latent_dim

    # Rebuild models
    generator = build_generator()
    discriminator = build_discriminator()

    # Define optimizers
    generator_optimizer = tf.keras.optimizers.Adam(learning_rate=lr, beta_1=beta1)
    discriminator_optimizer = tf.keras.optimizers.Adam(learning_rate=lr, beta_1=beta1)

    # Dummy training function for now (you can replace with real one)
    def dummy_train(generator, discriminator, epochs=2):
        # Simulate score (or replace with loss/FID)
        return np.random.uniform(0.7, 1.0)

    # Train for few epochs and get dummy score
    score = dummy_train(generator, discriminator)

    # Store results
    tuning_results.append({
        'learning_rate': lr,
        'batch_size': batch_size,
        'latent_dim': latent_dim,
        'beta_1': beta1,
        'score': score
    })

 Run 1/16
LR=0.0002, Batch=32, Latent=100, Beta1=0.5

 Run 2/16
LR=0.0002, Batch=32, Latent=100, Beta1=0.6

 Run 3/16
LR=0.0002, Batch=32, Latent=128, Beta1=0.5

 Run 4/16
LR=0.0002, Batch=32, Latent=128, Beta1=0.6

 Run 5/16
LR=0.0002, Batch=64, Latent=100, Beta1=0.5

 Run 6/16
LR=0.0002, Batch=64, Latent=100, Beta1=0.6

 Run 7/16
LR=0.0002, Batch=64, Latent=128, Beta1=0.5

 Run 8/16
LR=0.0002, Batch=64, Latent=128, Beta1=0.6

 Run 9/16
LR=0.0001, Batch=32, Latent=100, Beta1=0.5

 Run 10/16
LR=0.0001, Batch=32, Latent=100, Beta1=0.6

 Run 11/16
LR=0.0001, Batch=32, Latent=128, Beta1=0.5

 Run 12/16
LR=0.0001, Batch=32, Latent=128, Beta1=0.6

 Run 13/16
LR=0.0001, Batch=64, Latent=100, Beta1=0.5

 Run 14/16
LR=0.0001, Batch=64, Latent=100, Beta1=0.6

 Run 15/16
LR=0.0001, Batch=64, Latent=128, Beta1=0.5

 Run 16/16
LR=0.0001, Batch=64, Latent=128, Beta1=0.6

In [53]:
# Convert results to DataFrame
results_df = pd.DataFrame(tuning_results)

# Sort by highest score
results_df = results_df.sort_values(by='score', ascending=False)
display(results_df)

    learning_rate  batch_size  latent_dim  beta_1     score
1          0.0002          32         100     0.6  0.996978
11         0.0001          32         128     0.6  0.991268
15         0.0001          64         128     0.6  0.974154
7          0.0002          64         128     0.6  0.964331
5          0.0002          64         100     0.6  0.945325
13         0.0001          64         100     0.6  0.931316
2          0.0002          32         128     0.5  0.919081
6          0.0002          64         128     0.5  0.914950
12         0.0001          64         100     0.5  0.911839
10         0.0001          32         128     0.5  0.826970
8          0.0001          32         100     0.5  0.822822
9          0.0001          32         100     0.6  0.819936
14         0.0001          64         128     0.5  0.797657
4          0.0002          64         100     0.5  0.789992
0          0.0002          32         100     0.5  0.786280
3          0.0002          32         128     0.6  0.754850